{% set name = "activitysim" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/activitysim-{{ version }}.tar.gz
  sha256: 54d3c5d1cdf27e387729cf97b9ee013d447fda15362cfd5cac9438bf34c4c666

build:
  number: 0
  noarch: python
  entry_points:
    - activitysim=activitysim.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - cytoolz >=0.8.1
    - numba >=0.51.2
    - numpy >=1.16.1
    - openmatrix >=0.3.4.1
    - orca >=1.6
    - pandas >=1.1.0
    - psutil >=4.1
    - pyarrow >=2.0
    - python >=3.9
    - pyyaml >=5.1
    - requests >=2.7
    - pytables >=3.5.1

test:
  imports:
    - activitysim
    - activitysim.abm
  commands:
    - pip check
    - activitysim --help
  requires:
    - pip

about:
  home: https://github.com/activitysim/activitysim
  summary: Activity-Based Travel Modeling
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jpn--
    - bstabler
    - danielsclint
